require("@rails/ujs").start()
require("turbolinks").start()
require("@rails/activestorage").start()
require("channels")
require("jquery")
require("bootstrap")
require("packs/home")
require ("packs/jquery.raty")
require ("packs/ratyrate.js.erb")
